# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bcfef130d14b995e238eb440ac04ef4cbf1857a766164f5f347a7b611cd0b2717a34c0dc1a97a5dd4cadcf8b5405d00372b81fe062ab018cc158c1dc7c2677c7

test:
  secret_key_base: 4dcf1316aadb55035f88c76e5be1f03284ad5d6696a1ca39b6537dbfab51421f95ae76a85694470776df8ff7fa9d51b4dcc709619c6d461a418566a095a5304c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
